/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

/**
 *
 * @author Davi
 */
public class CursoSave extends javax.swing.JFrame {
    
    private br.com.ifba.curso.controller.CursoController cursoController; // controller gerenciado pelo Spring
    
    private br.com.ifba.curso.entity.Curso curso; // variável para guardar o curso

            public CursoSave(br.com.ifba.curso.entity.Curso curso) { // construtor usado para edição

    initComponents(); // inicializa os componentes da tela

    cursoController = br.com.ifba.Prg03persistenciaApplication.contexto.getBean(br.com.ifba.curso.controller.CursoController.class); // pega o controller do Spring

    this.curso = curso; // guarda o curso recebido

    txtNome.setText(curso.getNome()); // preenche o campo nome

    txtDescricao.setText(curso.getDescricao()); // preenche o campo descrição

    txtCargaHoraria.setText(String.valueOf(curso.getCargaHoraria())); // preenche o campo carga horária

            } // fim do construtor
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoSave.class.getName());

    /**
     * Creates new form CursoSave
     */
    public CursoSave() { // construtor padrão

    initComponents(); // inicializa os componentes da tela

    cursoController = br.com.ifba.Prg03persistenciaApplication.contexto.getBean(br.com.ifba.curso.controller.CursoController.class); // pega o controller do Spring

} // fim do construtor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblCargaHoraria = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtCargaHoraria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("CADASTRO DE CURSO ");

        lblNome.setText("Nome:");

        lblDescricao.setText("Descrição:");

        lblCargaHoraria.setText("Carga Horária:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDescricao)
                                .addGap(18, 18, 18)
                                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(18, 18, 18)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))
                            .addComponent(lblTitulo))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCargaHoraria)
                        .addGap(18, 18, 18)
                        .addComponent(txtCargaHoraria)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargaHoraria)
                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
      this.dispose(); // fecha a tela 
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    
           try { // inicia o bloco de tentativa

        String nome = txtNome.getText(); // obtém o texto digitado no campo nome

        String descricao = txtDescricao.getText(); // obtém o texto digitado no campo descrição

        int carga = Integer.parseInt(txtCargaHoraria.getText()); // converte a carga horária para inteiro

        if (curso == null) { // verifica se é um novo cadastro

            curso = new br.com.ifba.curso.entity.Curso(); // cria um novo objeto Curso

        } // fim do if

        curso.setNome(nome); // define o nome do curso

        curso.setDescricao(descricao); // define a descrição do curso

        curso.setCargaHoraria(carga); // define a carga horária do curso

        cursoController.salvar(curso); // salva ou atualiza o curso usando a controller do Spring

        javax.swing.JOptionPane.showMessageDialog( // exibe mensagem para o usuário
                this, // usa a tela atual como referência
                "Salvo com sucesso!", // mensagem exibida
                "Sucesso", // título da janela
                javax.swing.JOptionPane.INFORMATION_MESSAGE // tipo da mensagem
        ); // fim da mensagem

        this.dispose(); // fecha a tela após salvar

    } catch (Exception e) { // captura qualquer erro que acontecer

        javax.swing.JOptionPane.showMessageDialog( // exibe mensagem de erro
                this, // usa a tela atual como referência
                "Erro: " + e.getMessage(), // mostra a mensagem do erro
                "Erro", // título da janela
                javax.swing.JOptionPane.ERROR_MESSAGE // tipo da mensagem
        ); // fim da mensagem de erro

    } // fim do catch

    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CursoSave().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCargaHoraria;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCargaHoraria;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
