/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

/**
 *
 * @author Davi
 */
public class CursoListar extends javax.swing.JFrame {
    
    private void carregarTabelaFiltro(String texto) { // método para carregar tabela com filtro

    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblCursos.getModel(); // pega modelo

    modelo.setRowCount(0); // limpa tabela

    java.util.List<br.com.ifba.curso.entity.Curso> lista = new br.com.ifba.curso.dao.CursoDAO().buscarPorNome(texto); // busca filtrada

    for (br.com.ifba.curso.entity.Curso c : lista) { // percorre resultados

        modelo.addRow(new Object[]{ // adiciona na tabela
            c.getId(),
            c.getNome(),
            c.getDescricao(),
            c.getCargaHoraria()
        });
    }
}
    
    private void carregarTabela() { // método para preencher a tabela

    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblCursos.getModel(); // pega modelo da tabela

    modelo.setRowCount(0); // limpa tabela

    java.util.List<br.com.ifba.curso.entity.Curso> lista = new br.com.ifba.curso.dao.CursoDAO().listar(); // busca do banco

    for (br.com.ifba.curso.entity.Curso c : lista) { // percorre lista

        modelo.addRow(new Object[]{ // adiciona linha
            c.getId(), // id
            c.getNome(), // nome
            c.getDescricao(), // descrição
            c.getCargaHoraria() // carga
        });
    }
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoListar.class.getName());

    /**
     * Creates new form CursoListar
     */
    public CursoListar() {
        initComponents();
        carregarTabela(); // carrega ao abrir
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblBusca = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("GERENCIAMENTO DE CURSOS");

        lblBusca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBusca.setText("BUSCAR:");

        txtBusca.addActionListener(this::txtBuscaActionPerformed);

        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(this::btnPesquisarActionPerformed);

        btnNovo.setText("+");
        btnNovo.addActionListener(this::btnNovoActionPerformed);

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Descrição", "Carga Horária"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCursos);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(this::btnAtualizarActionPerformed);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(this::btnRemoverActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBusca)
                                .addGap(18, 18, 18)
                                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar)))
                        .addGap(38, 38, 38)
                        .addComponent(btnNovo)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(btnAtualizar)
                .addGap(101, 101, 101)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemover)
                .addGap(183, 183, 183))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitulo)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusca)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnNovo))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnRemover))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
    CursoSave tela = new CursoSave(); // cria uma nova instância da tela de cadastro

    tela.setVisible(true); // deixa a tela visível        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
    carregarTabela(); // chama o método que recarrega os dados da tabela

    javax.swing.JOptionPane.showMessageDialog( // exibe uma mensagem na tela
            this, // usa a janela atual como referência
            "Cursos atualizados com sucesso!", // texto da mensagem
            "Informação", // título da janela
            javax.swing.JOptionPane.INFORMATION_MESSAGE // tipo da mensagem
    ); // fim da criação da mensagem 
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
         
        int linha = tblCursos.getSelectedRow(); // obtém a linha selecionada

    if (linha >= 0) { // verifica se existe seleção

        int confirmacao = javax.swing.JOptionPane.showConfirmDialog( // abre caixa de confirmação
                this, // referência da tela atual
                "Tem certeza que deseja remover este curso?", // mensagem
                "Confirmação", // título
                javax.swing.JOptionPane.YES_NO_OPTION // opções
        ); // fim da confirmação

        if (confirmacao == javax.swing.JOptionPane.YES_OPTION) { // verifica se clicou em sim

            Long id = Long.parseLong(tblCursos.getValueAt(linha, 0).toString()); // obtém o ID

            new br.com.ifba.curso.dao.CursoDAO().remover(id); // remove o curso do banco

            carregarTabela(); // atualiza a tabela

            javax.swing.JOptionPane.showMessageDialog( // exibe mensagem de sucesso
                    this, // referência da tela
                    "Curso removido com sucesso!", // texto
                    "Sucesso", // título
                    javax.swing.JOptionPane.INFORMATION_MESSAGE // tipo
            ); // fim da mensagem

        } // fim do if interno

    } else { // caso nenhuma linha selecionada

        javax.swing.JOptionPane.showMessageDialog( // exibe aviso
                this, // referência da tela
                "Selecione um curso para remover!", // mensagem
                "Aviso", // título
                javax.swing.JOptionPane.WARNING_MESSAGE // tipo
        ); // fim da mensagem

    } // fim do else
    
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    int linha = tblCursos.getSelectedRow(); // obtém a linha selecionada na tabela

    if (linha >= 0) { // verifica se alguma linha foi selecionada

        Long id = Long.parseLong(tblCursos.getValueAt(linha, 0).toString()); // obtém o ID da linha selecionada

        br.com.ifba.curso.entity.Curso curso = null; // cria variável para armazenar o curso

        for (br.com.ifba.curso.entity.Curso c : new br.com.ifba.curso.dao.CursoDAO().listar()) { // percorre todos os cursos do banco
            if (c.getId().equals(id)) { // verifica se o ID corresponde
                curso = c; // armazena o curso encontrado
                break; // sai do loop
            } // fim do if
        } // fim do for

        CursoSave tela = new CursoSave(curso); // cria a tela de edição com os dados

        tela.setVisible(true); // exibe a tela

    } else { // caso nenhuma linha tenha sido selecionada

        javax.swing.JOptionPane.showMessageDialog( // exibe mensagem de aviso
                this, // referência da tela atual
                "Selecione um curso para editar!", // texto da mensagem
                "Aviso", // título
                javax.swing.JOptionPane.WARNING_MESSAGE // tipo de mensagem
        ); // fim da mensagem

    } // fim do else
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
    String texto = txtBusca.getText(); // pega o texto digitado

    if (texto == null || texto.trim().isEmpty()) { // verifica se está vazio

        carregarTabela(); // carrega tudo se não digitou nada

    } else {

        carregarTabelaFiltro(texto); // aplica filtro
    }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CursoListar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
